### ISSUE TITLE
adding phpmyadmin - connection error

### ISSUE THREAD

**Issue by pixeline** [banesto/docker-php5.3-dev#1]
Hello!

Thanks a lot for this : i'm using it to work on an old (huge) codebase I recently received. I would like to add phpMyAdmin to be able to tweak the database structure. I added it to the docker-compose.yml file, as such:

```yml 
version: '2'
services:
  app:
    image: banesto/docker-php5.3-dev
    container_name: web
    volumes:
      - ./php5-public:/var/www/html
      - ./.database:/var/lib/mysql
      - ./sql:/sql
      - ./logs:/etc/httpd/logs
    ports:
      - "1973:80"
      - "33066:3306"
    stdin_open: true
    environment:
      DB_NAME: dbname
      DB_USER: test
      DB_PASS: test
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4
    container_name: pma
    links:
      - app
    depends_on:
      - app
    environment:
      PMA_HOST: web
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 1974:80
```

When I visit the localhost:1974, I see the phpmyadmin login screen. I then login successfully but as soon as i land on the PMA dashboard I get this error message:
> Error in processing request Error code: 200
> Error text: OK (rejected)
> It seems that the connection to server has been lost. Please check your network connectivity and server status.

I tried with latest phpmyadmin as well, same error. Would you have an idea on how to make it work?

**Comment by banesto** [comment]
Hi! I haven't run multiple services at once, and neither phpmyadmin on docker, so it's hard to say. Is app running ok (there is connection to DB)?

**Comment by pixeline** [comment]
It turns out there was an incompatibility between pma and the old mysql server 5.1. Using an old PMA version solved it.

Here is how it works now:

```yml
version: '2.1'
services:
  app:
    image: banesto/docker-php5.3-dev
    container_name: web
    volumes:
      - ./php5-public:/var/www/html
      - ./.database:/var/lib/mysql
      - ./sql:/sql
      - ./logs:/etc/httpd/logs
    ports:
      - "1973:80"
      - "33066:3306"
    stdin_open: true
    restart: always
    environment:
      DB_NAME: dbname
      DB_USER: test
      DB_PASS: test
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  pma:
    image: dnhsoft/phpmyadmin:4.0.0
    links:
      - app
    ports:
      - "1974:80"
    environment:
      DBHOST: web
      DBUSER: test
      DBPASS: test
```

Thanks!
